<style lang="scss">
    $green-vue: #42b983;
    .fb{
        color: $green-vue;
        text-decoration: underline !important;
    }
    .fb:hover{
        color: #20895e !important;
    }
</style>

<template>   
    <div class="home">
        <h1>Hello!</h1>
        <h4>Please choose sorting algorithm you want to play in side bar</h4>
        <hr>
        <h4>Author: <a href="https://facebook.com/cpt.jack1998" class="fb">Pham Dung</a></h4>
        <h4>Created at: 10/2017</h4>
    </div>
</template>

